# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: pip # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect
      - dependency-name: "host-tools"
        source:
          type: "git"
          url: "https://github.com/l8556/host_tools.git"
      - dependency-name: "telegram"
        source:
          type: "git"
          url: "https://github.com/l8556/TelegramApi.git"
      - dependency-name: "VBoxWrapper"
        source:
          type: "git"
          url: "https://github.com/l8556/VBoxWrapper.git"
      - dependency-name: "ssh-wrapper"
        source:
          type: "git"
          url: "https://github.com/l8556/SshWrapper.git"
